


CELL_SIZE = 30
BOARD_WIDTH = 10
BOARD_HEIGHT = 20
SIDE_PANEL_INCREMENT = 6

SCREEN_HEIGHT = CELL_SIZE * BOARD_HEIGHT
SIDE_PANEL_WIDTH = CELL_SIZE * SIDE_PANEL_INCREMENT
SCREEN_WIDTH = CELL_SIZE * BOARD_WIDTH + SIDE_PANEL_WIDTH

GAME_FONT = 'Consolas'
GAME_FONT_SIZE = 20

FALL_SPEED = 800
FALL_ACCELERATION = 0.85  # Reduce un 15% por nivel
MOVE_DELAY = 50

LEVEL_UP_LINES = 10
SCORE_PER_LINE = 100
TETRIS_BONUS = 400